# Site settings
title: Precious Aitanun
author: Precious Aitanun
email: paitanun35@gmail.com
description: Exploring the intersection of medicine, creativity, and technology. I craft stories and visuals while decoding the human bodyâ€”one pixel and pulse at a time.
lang: en
baseurl: ""
url: "https://nadira3.github.io"

# Social media
twitter_username: techdoctorP
github_username: Nadira3
linkedin_username: precious-aitanun

# Collections
collections:
  posts:
    output: true
  projects:
    output: true
  journal:
    output: true

markdown: GFM

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

# Blog settings
pagination:
  enabled: true

exclude:
  - README.md
